feat: transfer button
fractaldotbox/geist-dapp-kit pull request #22
Opened 2024-11-02 15:53 UTC by iyansr

<img width="309" alt="image" src="https://github.com/user-attachments/assets/174fb478-1d57-41b6-afe0-4f66beb51e34">

2024-11-03 13:10 UTC, justin-lau requested changes

2024-11-03 13:10 UTC, justin-lau commented on apps/storybook/src/stories/transfer-button/transfer-button.stories.tsx
> +      </div>
nit: think we should avoid overlapping.

<img width="217" alt="image" src="https://github.com/user-attachments/assets/0aca8eb1-36c1-46bf-97c8-3916fdd25350">

2024-11-03 13:10 UTC, justin-lau commented on apps/storybook/src/stories/transfer-button/transfer-button.tsx
> +    </Button>
nit: could add shadcn's loading icon: https://ui.shadcn.com/docs/components/button#loading

2024-11-05 16:06 UTC, justin-lau requested changes

2024-11-05 16:06 UTC, justin-lau commented on apps/storybook/src/stories/transfer-button/transfer-button.stories.tsx
> +            if (/^[0-9]*\.?[0-9]*$/.test(value)) {
This regex also matches empty string because everything is optional.

```suggestion
            if (/^([0-9]+\.)?[0-9]+$/.test(value)) {
```

2024-11-05 16:10 UTC, justin-lau commented on apps/storybook/src/stories/transfer-button/transfer-button.stories.tsx
> +            if (/^[0-9]*\.?[0-9]*$/.test(value)) {
Would be best if you can throw in a test case for this. Not required to merge though.

2024-11-08 14:15 UTC, justin-lau requested changes
Thank you for fixing the regex. I’ve realized there might be a UX issue with this implementation.

When a user wants to completely replace the value, they might select all text and start typing an integer. However, it’s also common for users to select all and press backspace to clear the textbox before typing again. With the updated regex making empty space invalid, backspace cannot be used to clear the text completely.

On the other hand, I believe it’s important to disable the transfer button when the textbox doesn’t contain a valid amount, including when it’s empty.

If you agree this would provide a better UX, could you update the transfer button to accept a `disabled` prop? Then, we could set `disabled={!isValid}`, where `isValid` would be the result of the regex test.

2024-11-10 15:01 UTC, iyansr commented
Hi @justin-lau I made few adjustment
- Extending button props, so we can use `disabled` props
- When user pressing `Backspace` it will remove the input
- Disabled the button when input is not valid

2024-11-11 10:04 UTC, justin-lau requested changes

2024-11-11 10:04 UTC, justin-lau commented on apps/storybook/src/stories/transfer-button/transfer-button.stories.tsx
> +				/>
This does not handle cases where multiple characters are selected when pressing backspace.

Additionally, this is beginning to over-engineer the browser’s native behavior for this control, which may introduce unintended side effects. Now that isValid has been introduced, I think simply reverting to type="number" would resolve the UX issues.

```suggestion
        <input
          placeholder="0"
          type="number"
          value={String(amount)}
          onChange={(e) => setAmount(e.target.value)}
          className="border-none bg-white outline-none focus-within:outline-none px-4 focus:outline-none h-10 flex-1"
        />
```

2024-11-12 05:29 UTC, merged